name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Zip Artifact
      run: zip -r app.zip .

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIAQETNHJ4A4QCBRUND
        aws-secret-access-key: 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
        aws-region: ap-south-1b

    - name: Upload to S3
      run: aws s3 cp app.zip s3://pbizapps-artifacts-bucket/

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws s3 cp s3://pbizapps-artifacts-bucket/app.zip .
          unzip -o app.zip
          chmod +x app.sh
          ./app.sh

